name = "streeteasy-monitor"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "streeteasy-monitor"
database_id = "fd2e0d03-1aaf-4afc-b1bd-88de7c687bb8"
